### ISSUE TITLE
rading-indicator/indicators/atr.js:14

### ISSUE THREAD

**Issue by ghostnetrn** [thanhnguyennguyen/trading-indicator#45]
rading-indicator/indicators/atr.js:14
        }
        ^

SyntaxError: Unexpected token '}'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/root/trading-indicator/index.js:15:8)

**Comment by thanhnguyennguyen** [comment]
please update to version 1.0.6
